// CODE GENERATED by `strimserver-controller -print-ts-types`. DO NOT EDIT.
// Source of truth: core/controller/names.go + controller.go

export type PathStatus = "unknown" | "ready" | "not-ready";
export type StageState = "running" | "stopped" | "";
export type PathName  = "ingress0" | "normalized";
export type StageName = "mediamtx" | "normalize" | "scale_and_egress";

export interface StageStatus { desired: StageState; actual: StageState; }
export interface ControllerStatus {
   paths: Record<PathName, PathStatus>;
   stages: Record<StageName, StageStatus>;
}

export const Stages = { MediaMTX: "mediamtx", Normalize: "normalize", ScaleAndEgress: "scale_and_egress" } as const;
export type ControlComponent = "scale_and_egress";
export type ControlAction    = "start" | "stop";
