#!/bin/sh

aws cloudformation deploy \
  --template-file deploy/aws/strimserver-infra.yaml \
  --stack-name strimserver \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
      CreateNetwork="true" \
      OperatorCidr="$OPERATOR_CIDR" \
      IngestCidr="$OPERATOR_CIDR" \
      EnableExperimentalSsh="true" \
      DeploymentBucketName="$S3_BUCKET_NAME"   # omit when using https/local deploy
