#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="${1:-core/strimserver.env}"

REQUIRED_ENV_VARS=(
  CONTAINERD_SOCKET CONTAINERD_NAMESPACE
  CONTROLLER_RECONCILE_INTERVAL CONTROLLER_INFLIGHT_TIMEOUT
  CONTROLLER_SHUTDOWN_TIMEOUT CONTROLLER_ACTIONS_BUFFER_SIZE CONTROLLER_HTTP_PORT
  STAGE_STOP_TIMEOUT WEBSOCKET_WRITE_TIMEOUT
  MEDIAMTX_CONTAINER_ID MEDIAMTX_SNAPSHOT_ID MEDIAMTX_IMAGE_NAME MEDIAMTX_LOG_FILE
  NORMALIZE_CONTAINER_ID NORMALIZE_SNAPSHOT_ID NORMALIZE_LOG_FILE
  EGRESS_CONTAINER_ID EGRESS_SNAPSHOT_ID EGRESS_LOG_FILE
  FFMPEG_IMAGE_NAME FFMPEG_NICE FFMPEG_LOG_LEVEL
  MEDIAMTX_NICE MEDIAMTX_CONFIG_TEMPLATE
  STRIMSERVER_SRT_PORT STRIMSERVER_RTSP_PORT NORMALIZED_MPEGTS_SOCKET
  MEDIAMTX_READ_TIMEOUT_DURATION
  NORMALIZED_VIDEO_BITRATE NORMALIZED_VIDEO_MAXRATE NORMALIZED_VIDEO_MINRATE
  NORMALIZED_VIDEO_BUFSIZE NORMALIZED_AUDIO_BITRATE
  SCALED_VIDEO_HEIGHT_PIXELS
  EGRESS_VIDEO_BITRATE EGRESS_VIDEO_MAXRATE EGRESS_VIDEO_MINRATE
  EGRESS_VIDEO_BUFSIZE EGRESS_AUDIO_BITRATE
  TWITCH_INGEST_SERVER TWITCH_STREAM_KEY BANDWIDTH_TEST
)

unset "${REQUIRED_ENV_VARS[@]}"

set -a; . "$ENV_FILE"; set +a
missing=0
for v in "${REQUIRED_ENV_VARS[@]}"; do
  if [ -z "${!v:-}" ]; then echo "missing or empty: $v" >&2; missing=1; fi
done
[ "$missing" -eq 0 ] && echo "env OK ($ENV_FILE)" || { echo "env check FAILED" >&2; exit 1; }

