package main

import (
   "context"
   "encoding/json"
   "errors"
   "flag"
   "fmt"
   "io"
   "log"
   "net/http"
   "os"
   "os/signal"
   "reflect"
   "strconv"
   "strings"
   "syscall"
   "time"

   "github.com/coder/websocket"
   "github.com/coder/websocket/wsjson"

   containerd "github.com/containerd/containerd/v2/client"
   "github.com/containerd/containerd/v2/pkg/namespaces"
   "github.com/containerd/containerd/api/events"
)

type ContainerConfig struct{ ContainerID, SnapshotID, ImageName, Logfile string }
type Config struct {
   ContainerdSocket, ContainerdNamespace, ControllerHTTPPort, HostRoot string
   ControllerReconcileInterval time.Duration
   ControllerInFlightTimeout time.Duration
   ControllerShutdownTimeout time.Duration
   StageStopTimeout time.Duration
   WebsocketWriteTimeout time.Duration
   ControllerActionsBufferSize uint8
   MediaMTX, Normalize, ScaleAndEgress ContainerConfig
}

func checkEnv() error {
   var errs []error
   for _, v := range envSpec() {
      if !v.Required { continue }
      if raw, ok := syscall.Getenv(v.Name); !ok || raw == "" {
         errs = append(errs, fmt.Errorf("missing or empty: %s", v.Name))
      }
   }
   return errors.Join(errs...)
}

func printEnvExample(w io.Writer) {
   var last Group
   for _, v := range envSpec() {
      if v.Group != last { _, _ = fmt.Fprintf(w, "\n# --- %s ---\n", v.Group); last = v.Group }
      if v.Comment != "" { _, _ = fmt.Fprintf(w, "# %s\n", v.Comment) }
      _, _ = fmt.Fprintf(w, "%s=%q\n", v.Name, v.Example)
   }
}

func printTSTypes(w io.Writer) {
   p := func(f string, a ...any) { _, _ = fmt.Fprintf(w, f+"\n", a...) }
   union := func(vals []string) string {
      q := make([]string, len(vals))
      for i, v := range vals { q[i] = strconv.Quote(v) }
      return strings.Join(q, " | ")
   }

   p("// CODE GENERATED by `strimserver-controller -print-ts-types`. DO NOT EDIT.")
   p("// Source of truth: core/controller/names.go + controller.go\n")
   p("export type PathStatus = %s;", union(toStrings(AllPathStatuses)))
   p("export type StageState = %s;", union(append(toStrings(AllStageStates), "")))
   p("export type PathName  = %s;", union(toStrings(AllPathNames)))
   p("export type StageName = %s;", union(toStrings(AllStageNames)))
   p("")
   p("export interface StageStatus { desired: StageState; actual: StageState; }")
   p("export interface ControllerStatus {")
   p("   paths: Record<PathName, PathStatus>;")
   p("   stages: Record<StageName, StageStatus>;")
   p("}")
   p("")
   p("export const Stages = { MediaMTX: %q, Normalize: %q, ScaleAndEgress: %q } as const;",
      StageMediaMTX, StageNormalize, StageScaleAndEgress)
   p("export type ControlComponent = %s;", union(toStrings(AllControlComponents)))
   p("export type ControlAction    = %s;", union(toStrings(AllControlActions)))
}

func LoadConfig() (Config, error) {
   var cfg Config
   var errs []error
   for _, v := range envSpec() {
      raw, found := syscall.Getenv(v.Name)
      if !found || raw == "" {
         if v.Required { errs = append(errs, fmt.Errorf("missing required env var %q", v.Name)) }
         continue
      }
      if v.Bind != nil {
         err := v.Bind(&cfg, raw)
         if err != nil { errs = append(errs, fmt.Errorf("could not parse %q = %q: %w", v.Name, raw, err)) }
      }
   }
   if len(errs) > 0 { return Config{}, errors.Join(errs...) }
   return cfg, nil
}

func main() {
   checkEnvFlag := flag.Bool("check-env", false, "validate required env vars and exit")
   printExample := flag.Bool("print-env-example", false, "write .env.example to stdout and exit")
   printTS := flag.Bool("print-ts-types", false, "write the TS wire types to stdout and exit")
   flag.Parse()

   switch {
      case *printExample: printEnvExample(os.Stdout)
      case *printTS: printTSTypes(os.Stdout)
      case *checkEnvFlag: err := checkEnv(); if err != nil { log.Fatal(err) }; fmt.Println("env OK")
      default: err := run(); if err != nil { log.Fatal(err) }
   }

}

func run() error {
   config, err := LoadConfig()
   if err != nil { return fmt.Errorf("could not load config: %w", err) }

   rootContext, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
   nsCtx := namespaces.WithNamespace(rootContext, config.ContainerdNamespace)

   client, err := containerd.New(config.ContainerdSocket)
   if err != nil { return fmt.Errorf("could not initialize containerd client: %w", err) }
   defer func() { _ = client.Close() }()

   // build the container factory

   containerIDtoStageName := map[string]StageName {
      config.MediaMTX.ContainerID:        StageMediaMTX,
      config.Normalize.ContainerID:       StageNormalize,
      config.ScaleAndEgress.ContainerID:  StageScaleAndEgress,
   }

   containerFactory, err := NewContainerFactory(
      client, containerIDtoStageName, config.StageStopTimeout, DefaultLayout(config.HostRoot))
   if err != nil { return fmt.Errorf("could not create container factory: %w", err) }

   // build the mediamtx operations
   createFunc := func(ctx context.Context) (containerd.Container, string, error) {
      cfg := config.MediaMTX
      container, err := containerFactory.CreateMediaMTXContainer(
         ctx, cfg.ContainerID, cfg.SnapshotID, cfg.ImageName)
      return container, cfg.Logfile, err
   }

   lookupFunc := func(ctx context.Context) (containerd.Container, error) {
      return containerFactory.client.LoadContainer(ctx, config.MediaMTX.ContainerID)
   }

   mediamtxOps := containerFactory.CreateContainerOps(StageMediaMTX, createFunc, lookupFunc)

   // build the controller
   paths := map[PathName]PathStatus { PathIngress0: Unknown, PathNormalized: Unknown }

   pathEventRoutes := map[PathEvent]StageTarget {
      { Path: PathIngress0,    Status: Ready     }: { Stage: StageNormalize,        State: Running },
      { Path: PathIngress0,    Status: NotReady  }: { Stage: StageNormalize,        State: Stopped },
   }

   commandRoutes := map[ControlCommand]StageTarget {
      { Component: ComponentScaleAndEgress, Action: ActionStart }: { Stage: StageScaleAndEgress, State: Running,
         Prerequisite: func(c *Controller) error {
            if c.paths[PathNormalized] != Ready { return fmt.Errorf("normalized path is not ready") }; return nil
         },
      },
      { Component: ComponentScaleAndEgress, Action: ActionStop }: { Stage: StageScaleAndEgress, State: Stopped },
   }

   stages := map[StageName]*Stage{
      StageMediaMTX: {
         Status: StageStatus{ Desired: Running, Actual: Stopped }, Ops: mediamtxOps,
      },
      StageNormalize: {
         Status: StageStatus{ Desired: Stopped, Actual: Stopped },
         Ops: containerFactory.CreateStageOps(config.Normalize),
      },
      StageScaleAndEgress: {
         Status: StageStatus{ Desired: Stopped, Actual: Stopped },
         Ops: containerFactory.CreateStageOps(config.ScaleAndEgress),
      },
   }

   now := time.Now // function pointer - not a time value
   inflightTimeout := config.ControllerInFlightTimeout
   actionsBufferSize := config.ControllerActionsBufferSize

   controller, err := NewController(
      nsCtx, paths, stages, pathEventRoutes, commandRoutes,
      now, inflightTimeout, actionsBufferSize,
   )
   if err != nil { return fmt.Errorf("error constructing controller: %w", err) }

   log.Printf("%+v", controller)

   // wire up HTTP listener
   mux := http.NewServeMux()

   mux.HandleFunc("/event", postJSON(controller, (*Controller).SubmitPathEvent))

   mux.HandleFunc("/control", postJSON(controller, (*Controller).SubmitControl))

   mux.HandleFunc("/status", getJSON(controller, (*Controller).Status))

   mux.HandleFunc("/subscribe", func(w http.ResponseWriter, r *http.Request) {
      conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{ InsecureSkipVerify: true })
      if err != nil { log.Printf("ws accept error: %v", err); return }

      ctx, cancel := context.WithCancel(rootContext)
      defer cancel()
      ctx = conn.CloseRead(ctx)

      sendChannel := make(chan *ControllerStatus, 1)
      listener := ControllerListener(func(status *ControllerStatus) {
         select {
            case sendChannel <- status:
            default:
               select { case <-sendChannel: default: }
               select { case sendChannel <- status: default: }
         }
      })

      err = controller.SubmitAddListener(&listener)
      if err != nil {
         log.Printf("could not add ControllerListener for ws client %q: %v", r.RemoteAddr, err)
         _ = conn.Close(websocket.StatusInternalError, err.Error()); return
      }
      defer func() {
         done := make(chan struct{})
         go func() {
            defer close(done)
            err := controller.SubmitRemoveListener(&listener)
            if err != nil { log.Printf("could not remove ControllerListener for ws client %q: %v", r.RemoteAddr, err) }
         }()
         select { case <-done: case <-time.After(time.Second): }
      }()

      // writer
      for {
         select {
            case <-ctx.Done():
               _ = conn.Close(websocket.StatusNormalClosure, "")
               return
            case status := <-sendChannel:
               wctx, cancel := context.WithTimeout(ctx, config.WebsocketWriteTimeout)
               err := wsjson.Write(wctx, conn, status); cancel()
               if err != nil {
                  log.Printf("ws write error: %v", err)
                  _ = conn.Close(websocket.StatusInternalError, err.Error()); return
               }
         }
      }
   })

   mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
      w.WriteHeader(http.StatusOK)
      _, err := w.Write([]byte("ok\n"))
      if err != nil {
         log.Printf("healthz endpoint error: %+v", err)
      }
   })

   // wire up containerd listener
   topicFilters := []string { `topic~="/tasks/.*"` }
   eventTypeToStageState := map[reflect.Type]StageState {
      reflect.TypeFor[*events.TaskStart]():   Running,
      reflect.TypeFor[*events.TaskExit]():    Stopped,
   }

   listenForContainerdEvents := containerFactory.CreateContainerdEventListener(
      topicFilters, eventTypeToStageState)

   log.Printf("starting control plane...")

   // Start the controller loop
   runDone := make(chan struct{})
   go func() { controller.Run(); close(runDone) }()

   // Start the containerd loop
   listenerDone := make(chan struct{})
   go func() {
      listenForContainerdEvents(nsCtx, controller)
      close(listenerDone)
   }()

   // Start the reconcile loop
   tickerDone := make(chan struct{})
   go func() {
      invokeReconcileEvery(nsCtx, controller, config.ControllerReconcileInterval)
      close(tickerDone)
   }()

   // Start the HTTP server loop
   addr := fmt.Sprintf(":%s", config.ControllerHTTPPort)

   srv := &http.Server{ Addr: addr, Handler: mux }
   go func() {
      log.Printf("controller listening on %s", addr)
      err := srv.ListenAndServe()
      if err != nil && !errors.Is(err, http.ErrServerClosed) {
         log.Printf("http server error: %v", err)
         stop()
      }
   }()

   <-rootContext.Done()
   stop()
   log.Printf("shutting down")

   shutdownCtx, cancel := context.WithTimeout(context.Background(), config.ControllerShutdownTimeout)
   defer cancel()

   err = srv.Shutdown(shutdownCtx)
   if err != nil {
      log.Printf("graceful http shutdown failed: %v", err)
      _ = srv.Close()
   }

   <-tickerDone
   <-listenerDone

   controller.WaitForOps()
   controller.Teardown()
   controller.Close()
   <-runDone

   return nil
}

func postJSON[T any](c *Controller, handle func(*Controller, T) error) http.HandlerFunc {
   return func(w http.ResponseWriter, r *http.Request) {

      if r.Method != http.MethodPost {
         http.Error(w, "method not allowed", http.StatusMethodNotAllowed); return
      }

      var message T
      err := json.NewDecoder(r.Body).Decode(&message)
      if err != nil {
         http.Error(w, fmt.Sprintf("bad json: %v", err), http.StatusBadRequest); return
      }

      err = handle(c, message)
      if err != nil { http.Error(w, err.Error(), http.StatusInternalServerError); return }
      c.RequestReconcile(); w.WriteHeader(http.StatusNoContent)
   }
}

func getJSON[T any](c *Controller, handle func(*Controller) T) http.HandlerFunc {
   return func(w http.ResponseWriter, r *http.Request) {

      if r.Method != http.MethodGet {
         http.Error(w, "method not allowed", http.StatusMethodNotAllowed); return
      }

      w.Header().Set("Content-Type", "application/json")

      err := json.NewEncoder(w).Encode(handle(c))
      if err != nil { log.Printf("json serialization error: %v", err) }
   }
}

func invokeReconcileEvery(ctx context.Context, c *Controller, interval time.Duration) {
   ticker := time.NewTicker(interval)
   defer ticker.Stop()
   for {
      select {
         case <-ctx.Done(): return
         case <-ticker.C: if ctx.Err() != nil { return }; c.RequestReconcile()
      }
   }
}

